@startuml
autonumber

title Add Title \nv0.1\n

autoactivate on

skinparam {
	defaultFontName Source Sans Pro

	DatabaseFontSize 12
	DatabaseBorderColor Gray
	DatabaseBackgroundColor White

	'hide footbox
	shadowing false
	lifelineStrategy solid
}

skinparam sequence {
	TitleFontSize 14

	ActorFontSize 12
	ActorBorderColor Gray
	ActorBackgroundColor White

	ParticipantFontSize 12
	ParticipantBorderColor Gray
	ParticipantBackgroundColor White

	BoxBorderColor White
	BoxBackgroundColor #FDF4DF
	BoxFontStyle normal

	LifeLineBorderColor #c0c0c0
	LifeLineBackgroundColor #ececeb

	ArrowColor Gray
	ArrowFontSize 11

	GroupBackgroundColor White
	GroupBorderColor #c0c0c0
	GroupBorderThickness 2
	GroupFontSize 14
	GroupFontStyle italic
	GroupHeaderFontSize 14
	GroupHeaderFontStyle normal
}


actor u as "User"
participant b2 as "Popup Window\n: Browser"
participant b1 as "Web Admin\n: Browser"
participant controller
database db as "database"
box "OIDC Provider"
	participant ae as "Authorization\n Endpoint"
	participant te as "Token\n Endpoint"
end box

@enduml
