---
Status: Current
Author(s): Mike Gaffney
Last Updated: September 21, 2017

---
[[sample-service]]
= Sample Service
:toc: preamble
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :star:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :children_crossing:
:warning-caption: :warning:
:sectnums:
endif::[]

This is the preamble for the Sample Service. Some text must be here or
the table of contents will not render.

== Background

Sometimes you want to note something in a foot.
footnote:[An example footnote.]

NOTE: This is an example of an note admonition block.

TIP: This is an example of an tip admonition block.

WARNING: This is an example of an warning admonition block.

CAUTION: This is an example of an caution admonition block.

IMPORTANT: This is an example of an important admonition block.

== Appendix

[glossary]
=== Glossary

[glossary]
Component:: refers to a runtime entity. Components are the principal
processing units and data stores that execute in a system. A component
has some runtime presence, such as processes, clients, servers, and data
stores. <<clements>>

[bibliography]
=== References

- [[[clements]]] P. Clements et al., _Documenting Software
  Architectures: Views and Beyond_, 2nd edition. Boston, MA, USA:
  Addison-Wesley Professional, 2010.
